### ISSUE TITLE
0.8.6 Compatibility error in console.log 

### ISSUE THREAD

**Issue by Jonwh25** [kandashi/Next-Up#86] opened 2021-06-01 22:57 UTC
Seeing this in the console.log
v0.8.6

![image](https://user-images.githubusercontent.com/60674327/120400048-05cb0f00-c2f2-11eb-9dec-5bf281bf5bff.png)

**Comment by kandashi** [comment] 2021-06-02 06:04
Duplicate of #84

**Closed** 2021-06-02 06:04 UTC
